services:
  db:
    image: mysql:8.3
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "8092:3306"

  web:
    image: php:8.3-apache
    environment:
      - APACHE_RUN_DIR=/var/run/apache2
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_PID_FILE=/var/run/apache2/apache2.pid
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    volumes:
      - ./:/var/www
      - ./docker-files/php.ini:/usr/local/etc/php/php.ini
      - ./docker-files/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker-files/apache2.conf:/etc/apache2/apache2.conf
    ports:
      - "8090:80"
    depends_on:
      - db
    build:
      context: .
    command: >
      bash -c "apt-get update &&
               apt-get install -y libpq-dev &&
               docker-php-ext-install pdo pdo_mysql &&
               (cd /var/www/; composer install) && 
               a2enmod rewrite &&
               (cd /var/www/; php /var/www/app/commands/seed.php) &&
               apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: test_user
      PMA_PASSWORD: test_password
      UPLOAD_LIMIT: 50M
    ports:
      - "8091:80"
    depends_on:
      - db

      